# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2357b59db9f4d6d855654a6e1df2c3a228ca5a134ba80d7ad90c26ee0a37bc590026a523ebe9b174df9e039480136f8e11cef435d84c42cd127504cf155478c

test:
  secret_key_base: 27554ad011e542a5e45d150b69eeec86aa5454c254cdc33fe7fd1a184678ebcaaeb0ba16b3b211851803cccd8e72efae3d377d574d310d70f5ede76ec2a5ad7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
